In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
'''Importing January 2020 Files 
Neighbourhoods = Neighbourhood list for geo filter. Sourced from city or open source GIS files.
Listings = 	Summary information and metrics for listings in Portland (good for visualisations).

Calendar_content = Detailed Calendar Data for listings in Portland
Listing_content = Detailed Listings data for Portland'''

neighborhoods20 = pd.read_csv('C:/Users/Jing/Desktop/Galvanize_Capstones/JingWu-Capstone2/DATA/neighborhoods.csv')
listings20 = pd.read_csv('C:/Users/Jing/Desktop/Galvanize_Capstones/JingWu-Capstone2/DATA/Jan2020listings.csv')

# Importing the csv.gz files
listings_content20 = pd.read_csv('C:/Users/Jing/Desktop/Galvanize_Capstones/JingWu-Capstone2/DATA/Jan2020listings.csv.gz')

'''Importing January 2017 files'''
listings17 = pd.read_csv('C:/Users/Jing/Desktop/Galvanize_Capstones/JingWu-Capstone2/DATA/2017listings.csv')
listings_content17 = pd.read_csv('C:/Users/Jing/Desktop/Galvanize_Capstones/JingWu-Capstone2/DATA/2017listings.csv.gz')

### Cleaning 2020 listings

In [3]:
# Dropping neighbourhood_group and other columns, renaming neighbourhood to neighborhood

listings20.columns
listings20.drop(columns=['neighbourhood_group','last_review','reviews_per_month','minimum_nights'],inplace=True)
listings20 = listings20.rename(columns={'neighbourhood': 'neighborhood'})

In [4]:
listings20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4578 entries, 0 to 4577
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4578 non-null   int64
 1   name                            4578 non-null   object
 2   host_id                         4578 non-null   int64
 3   host_name                       4578 non-null   object
 4   neighborhood                    4578 non-null   object
 5   latitude                        4578 non-null   float64
 6   longitude                       4578 non-null   float64
 7   room_type                       4578 non-null   object
 8   price                           4578 non-null   int64
 9   number_of_reviews               4578 non-null   int64
 10  calculated_host_listings_count  4578 non-null   int64
 11  availability_365                4578 non-null   int64
dtypes: float64(2), int64(6), object(4)
memory usage: 429.3+ KB

In [5]:
# Shows that hosts will have more than one listing. 
# Host_id 171371 has 3 listings, one of them is not available. (availability_365 is zero)
listings20.loc[listings20.host_id == 171371]

,id,name,host_id,host_name,neighborhood,latitude,longitude,room_type,price,number_of_reviews,calculated_host_listings_count,availability_365
3,39938,Friendly Guesthouse / 10 Min to Airport & Down...,171371,Sarah,Woodlawn,45.57428,-122.64594,Private room,29,274,3,0
642,5242273,Nice Guest House - 10 Min to Airport & Downtown,171371,Sarah,Woodlawn,45.57120,-122.64356,Private room,44,393,3,184
643,5242296,Friendly Guesthouse / 10 Min to Airport & Down...,171371,Sarah,Woodlawn,45.57049,-122.65005,Private room,29,294,3,29

In [6]:
# This host_id = 8534462 is a corporation that is renting out the airbnbs, 253 properties in total
listings20.loc[listings20.calculated_host_listings_count == listings20.calculated_host_listings_count.max()].head(2)

,id,name,host_id,host_name,neighborhood,latitude,longitude,room_type,price,number_of_reviews,calculated_host_listings_count,availability_365
3376,33017383,Pearl District Condos 1 BD 6,8534462,Corp Condos & Apts,Pearl,45.53173,-122.68647,Entire home/apt,190,1,253,31
3377,33039528,Market Street Condos Studio 4,8534462,Corp Condos & Apts,Portland Downtown,45.51550,-122.68636,Entire home/apt,180,12,253,252

In [7]:
listings20.room_type.value_counts()

Entire home/apt    3495
Private room       1050
Shared room          21
Hotel room           12
Name: room_type, dtype: int64

In [8]:
listings20 = listings20.loc[(listings20.room_type == 'Entire home/apt') | (listings20.room_type == 'Private room')]
listings20.reset_index(drop=True)

,id,name,host_id,host_name,neighborhood,latitude,longitude,room_type,price,number_of_reviews,calculated_host_listings_count,availability_365
0,16688,"Beautiful condo in downtown Pearl, NW Portland",64840,Ashish,Pearl,45.525420,-122.685570,Entire home/apt,275,78,1,362
1,29931,Lovely SW Victorian w/Bonus Room and Hot Tub,79786,Ken,Hayhurst,45.482780,-122.720890,Entire home/apt,200,53,3,306
2,37676,Mt. Hood View in the Pearl District,162158,Paul,Pearl,45.525550,-122.681930,Entire home/apt,125,123,2,335
3,39938,Friendly Guesthouse / 10 Min to Airport & Down...,171371,Sarah,Woodlawn,45.574280,-122.645940,Private room,29,274,3,0
4,41601,Grandpa's Bunkhouse-Backyard Studio,179045,Jean,Roseway,45.549350,-122.584250,Entire home/apt,130,219,2,365
...,...,...,...,...,...,...,...,...,...,...,...,...
4540,41181567,BEST NEIGHBORHOOD IN TOWN!,322907763,Sarah,Northwest District,45.535390,-122.702070,Entire home/apt,65,0,1,173
4541,41182490,Portland Single Room with all You Need 波特兰硬需求单人房,322737331,Zengjun,Montavilla,45.511520,-122.574100,Private room,23,0,1,28
4542,41184459,2-Bedroom Comfortable Hawthorne Apartment,310537626,Pat,Sunnyside,45.512550,-122.620150,Entire home/apt,66,0,1,337
4543,41211392,Hip backyard ADU for your temporary Portland stay,38396445,Cooper,Concordia,45.563900,-122.632000,Entire home/apt,60,0,1,121
4544,41230075,SW Portland Home less than 10 min from downtown,182664014,Jeff,Hayhurst,45.481589,-122.731952,Entire home/apt,300,0,1,13

In [9]:
listings20.drop(columns=['availability_365'],inplace=True)
listings20.head(1)

,id,name,host_id,host_name,neighborhood,latitude,longitude,room_type,price,number_of_reviews,calculated_host_listings_count
0,16688,"Beautiful condo in downtown Pearl, NW Portland",64840,Ashish,Pearl,45.52542,-122.68557,Entire home/apt,275,78,1

In [10]:
listings20.to_csv('listings_cleaned.csv',index=False)
# New listings file, deleted columns, reset index, updated neighborhoods, room_type, and availability_365

### Cleaning 2020 Listings_content

In [11]:
listings_content20.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [12]:
listings_content20.drop(columns=['listing_url','scrape_id','last_scraped','name','availability_365',
                               'experiences_offered','thumbnail_url','medium_url','picture_url','xl_picture_url',
                               'host_about','host_thumbnail_url','host_picture_url','neighborhood_overview','host_listings_count',
                               'host_neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed',
                              'city','state','country_code','country','latitude','longitude','is_location_exact','bed_type',
                              'host_id','host_url','host_since','host_total_listings_count','street','neighbourhood','square_feet','minimum_minimum_nights',
                               'maximum_minimum_nights','minimum_maximum_nights','maximum_maximum_nights','smart_location',
                              'reviews_per_month','jurisdiction_names','requires_license','license','calculated_host_listings_count_shared_rooms',
                               'calculated_host_listings_count_private_rooms','calculated_host_listings_count_entire_homes',
                              'calculated_host_listings_count','first_review','last_review','number_of_reviews_ltm','calendar_last_scraped','availability_90',
                               'availability_60','availability_30','maximum_nights_avg_ntm','minimum_nights_avg_ntm',
                              'host_name','require_guest_profile_picture','require_guest_phone_verification','host_location','market','notes',
                               'number_of_reviews','host_acceptance_rate','has_availability','calendar_updated'],inplace=True)

In [13]:
listings_content20.drop(columns=['review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value','host_verifications', 'weekly_price',
 'monthly_price','room_type'],inplace=True)

In [14]:
listings_content20 = listings_content20.loc[(listings_content20.minimum_nights >= 1) & (listings_content20.maximum_nights <= 14)]
listings_content20.head(2)

,id,summary,space,description,transit,access,interaction,house_rules,host_response_time,host_response_rate,...,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,review_scores_rating,instant_bookable,is_business_travel_ready,cancellation_policy
13,65466,We are frequent travelers who enjoy using AirB...,We are Scott and Suzi and we have an extra roo...,We are frequent travelers who enjoy using AirB...,Very accessible! 3 bus routes stop within 2 b...,"Private bedroom and bath, share the kitchen an...","You will be staying in our home with us, so we...",Please confirm your expected arrival time with...,within a few hours,100%,...,NaN,NaN,1,$0.00,2,14,98.0,f,f,moderate
21,94500,One room with queen size bed in a beautifully ...,Welcome to vintage Portland. This is an old ho...,One room with queen size bed in a beautifully ...,"Yes, 3 bus lines all very near my house. Airpo...",There aren't really any areas off limits. The ...,I am usually present while guests are staying....,"Hi, it's James. Welcome to my home. Just some ...",within a few hours,100%,...,$100.00,$10.00,1,$10.00,2,8,95.0,f,f,moderate

In [15]:
listings_content20 = listings_content20.loc[(listings_content20.bedrooms >= 1) & (listings_content20.bathrooms >= 1) & (listings_content20.beds >= 1)]

In [16]:
listings_content20.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 574 entries, 13 to 4577
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        574 non-null    int64
 1   summary                   572 non-null    object
 2   space                     514 non-null    object
 3   description               573 non-null    object
 4   transit                   513 non-null    object
 5   access                    474 non-null    object
 6   interaction               502 non-null    object
 7   house_rules               466 non-null    object
 8   host_response_time        524 non-null    object
 9   host_response_rate        524 non-null    object
 10  host_is_superhost         574 non-null    object
 11  host_has_profile_pic      574 non-null    object
 12  host_identity_verified    574 non-null    object
 13  zipcode                   572 non-null    object
 14  property_type             574 non-null    object
 15  accommodates              574 non-null    int64
 16  bathrooms                 574 non-null    float64
 17  bedrooms                  574 non-null    float64
 18  beds                      574 non-null    float64
 19  amenities                 574 non-null    object
 20  price                     574 non-null    object
 21  security_deposit          476 non-null    object
 22  cleaning_fee              521 non-null    object
 23  guests_included           574 non-null    int64
 24  extra_people              574 non-null    object
 25  minimum_nights            574 non-null    int64
 26  maximum_nights            574 non-null    int64
 27  review_scores_rating      557 non-null    float64
 28  instant_bookable          574 non-null    object
 29  is_business_travel_ready  574 non-null    object
 30  cancellation_policy       574 non-null    object
dtypes: float64(4), int64(5), object(22)
memory usage: 143.5+ KB

In [17]:
values = {'space':'', 'summary':'', 'transit':'', 'access':'', 'interaction':'', 'house_rules': '', 'host_reponse_time': '', 
         'host_response_rate':''}
listings_content20 = listings_content20.fillna(value=values)

In [18]:
values1 = {'description':'', 'host_response_time':'', 'security_deposit':'', 'cleaning_fee':'', 'review_scores_rating':''}
listings_content20 = listings_content20.fillna(value=values1)

In [19]:
listings_content20.loc[listings_content20.zipcode.isna()]
# two listings that don't have zipcodes

,id,summary,space,description,transit,access,interaction,house_rules,host_response_time,host_response_rate,...,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,review_scores_rating,instant_bookable,is_business_travel_ready,cancellation_policy
1033,9494512,Welcome to our hideout. Whether you're explor...,,Welcome to our hideout. Whether you're explor...,Plenty of free parking on the street and an op...,This the downstairs unit of a two floor duplex...,,- We live fulltime in the upstairs unit. Plea...,within an hour,100%,...,$500.00,$50.00,1,$0.00,2,6,98,f,f,strict_14_with_grace_period
2138,20591246,Private room(s) in close-in Rose City Park. C...,1 to 2 bedrooms depending on needs. When you b...,Private room(s) in close-in Rose City Park. C...,4 blocks away from bus line and 8 blocks from ...,The listing includes exclusive use of the upst...,We live on-site and are available by text to a...,- Quiet hours 9 pm - 8 am. We respectfully as...,within an hour,100%,...,$0.00,$25.00,2,$12.00,1,14,99,t,f,flexible

In [20]:
pd.set_option('display.max_rows', 35)
listings_content20.property_type.value_counts()

House                 275
Guest suite           139
Apartment              56
Bungalow               37
Guesthouse             29
Townhouse               9
Condominium             9
Tiny house              4
Loft                    3
Bed and breakfast       2
Boat                    2
Dome house              1
Treehouse               1
Other                   1
Hostel                  1
Cottage                 1
Boutique hotel          1
Houseboat               1
Serviced apartment      1
Cabin                   1
Name: property_type, dtype: int64

In [21]:
listings_content20 = listings_content20.loc[(listings_content20.property_type == 'House') | (listings_content20.property_type == 'Apartment') | (listings_content20.property_type == 'Guest suite')|
                    (listings_content20.property_type == 'Guesthouse') | (listings_content20.property_type == 'Condominium')
                    | (listings_content20.property_type == 'Bungalow') | (listings_content20.property_type == 'Townhouse')|
                    (listings_content20.property_type == 'Cottage') | (listings_content20.property_type == 'Loft')| 
                    (listings_content20.property_type == 'Tiny house') | (listings_content20.property_type == 'Bed and breakfast')]

In [22]:
listings_content20 = listings_content20.rename(columns={'id': 'listing_id'}).reset_index(drop=True)
listings_content20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   listing_id                564 non-null    int64
 1   summary                   564 non-null    object
 2   space                     564 non-null    object
 3   description               564 non-null    object
 4   transit                   564 non-null    object
 5   access                    564 non-null    object
 6   interaction               564 non-null    object
 7   house_rules               564 non-null    object
 8   host_response_time        564 non-null    object
 9   host_response_rate        564 non-null    object
 10  host_is_superhost         564 non-null    object
 11  host_has_profile_pic      564 non-null    object
 12  host_identity_verified    564 non-null    object
 13  zipcode                   562 non-null    object
 14  property_type             564 non-null    object
 15  accommodates              564 non-null    int64
 16  bathrooms                 564 non-null    float64
 17  bedrooms                  564 non-null    float64
 18  beds                      564 non-null    float64
 19  amenities                 564 non-null    object
 20  price                     564 non-null    object
 21  security_deposit          564 non-null    object
 22  cleaning_fee              564 non-null    object
 23  guests_included           564 non-null    int64
 24  extra_people              564 non-null    object
 25  minimum_nights            564 non-null    int64
 26  maximum_nights            564 non-null    int64
 27  review_scores_rating      564 non-null    object
 28  instant_bookable          564 non-null    object
 29  is_business_travel_ready  564 non-null    object
 30  cancellation_policy       564 non-null    object
dtypes: float64(3), int64(5), object(23)
memory usage: 136.7+ KB

In [23]:
listings_content20.to_csv('listingscontent_cleaned.csv',index=False)

### Cleaning 2017 listings data

In [24]:
listings17.columns
listings17.drop(columns=['neighbourhood_group','last_review','reviews_per_month','minimum_nights'],inplace=True)
listings17 = listings17.rename(columns={'neighbourhood': 'neighborhood'})

In [25]:
listings17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3814 entries, 0 to 3813
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              3814 non-null   int64
 1   name                            3814 non-null   object
 2   host_id                         3814 non-null   int64
 3   host_name                       3814 non-null   object
 4   neighborhood                    3814 non-null   object
 5   latitude                        3814 non-null   float64
 6   longitude                       3814 non-null   float64
 7   room_type                       3814 non-null   object
 8   price                           3814 non-null   int64
 9   number_of_reviews               3814 non-null   int64
 10  calculated_host_listings_count  3814 non-null   int64
 11  availability_365                3814 non-null   int64
dtypes: float64(2), int64(6), object(4)
memory usage: 357.7+ KB

In [26]:
listings17 = listings17.loc[(listings17.room_type == 'Entire home/apt') | (listings17.room_type == 'Private room')]
listings17.reset_index(drop=True)

,id,name,host_id,host_name,neighborhood,latitude,longitude,room_type,price,number_of_reviews,calculated_host_listings_count,availability_365
0,4209765,Oregon Convention Center,1770933,Anastasia,Sullivan's Gulch,45.533333,-122.642481,Private room,52,98,2,364
1,3635579,Spacious Room & Private Bath,274455,Eugenia,Sullivan's Gulch,45.532775,-122.648434,Private room,85,137,1,338
2,6019539,Private Suites near it all- Room #7,3029738,Phil,Sullivan's Gulch,45.531919,-122.648428,Private room,110,58,7,310
3,13031007,Best Neighborhood--3 Bed Apartment,636668,Sara Osheroff,Sullivan's Gulch,45.534087,-122.636626,Entire home/apt,95,25,1,349
4,6106997,"LOCATION NE! ""Mt Hood"" : King bed",17261537,Ian & Sharmil,Sullivan's Gulch,45.534491,-122.646883,Private room,65,121,7,325
...,...,...,...,...,...,...,...,...,...,...,...,...
3739,10230029,Cozy Studio In the Woods,141076,Jane,Arnold Creek,45.445301,-122.708912,Entire home/apt,60,2,2,273
3740,14886404,Private Garden Room near City,90122685,Ray,Far Southwest,45.437542,-122.740271,Private room,75,0,1,364
3741,6976600,Granny Flat in leafy SW Portland,31117446,Clare And Mike,Far Southwest,45.441046,-122.735728,Entire home/apt,125,4,1,179
3742,16489706,SW Portland Tiny House,24681582,Adam & Chelsea,Ashcreek,45.463834,-122.746934,Entire home/apt,100,1,1,159
3743,16316155,Art and serenity in upscale home,106773719,Sharon,Arnold Creek,45.434702,-122.716793,Private room,70,0,1,89

In [27]:
# listings17.drop(columns=['availability_365'],inplace=True)
listings17.head(1)

,id,name,host_id,host_name,neighborhood,latitude,longitude,room_type,price,number_of_reviews,calculated_host_listings_count,availability_365
0,4209765,Oregon Convention Center,1770933,Anastasia,Sullivan's Gulch,45.533333,-122.642481,Private room,52,98,2,364

In [28]:
listings17.to_csv('listings_cleaned2017.csv',index=False)

### Cleaning listings_content17 Data

In [29]:
listings_content17.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'],
      dtype='object')

In [30]:
listings_content17.drop(columns=['listing_url','scrape_id','last_scraped','experiences_offered','thumbnail_url',
                                'medium_url','picture_url','xl_picture_url','host_url','host_since','host_location',
                                'host_about','host_thumbnail_url','street','neighbourhood','neighbourhood_cleansed',
                                'neighbourhood_group_cleansed','state','market','smart_location','country_code','country',
                                'is_location_exact','room_type','square_feet','weekly_price','monthly_price','has_availability',
                                'availability_30', 'availability_60', 'availability_90','availability_365', 'calendar_last_scraped',
                                'first_review','last_review','review_scores_accuracy', 'review_scores_cleanliness','review_scores_checkin', 
                                'review_scores_communication','review_scores_location', 'review_scores_value', 'requires_license','license', 'jurisdiction_names',
                                'require_guest_profile_picture','require_guest_phone_verification', 'calculated_host_listings_count','reviews_per_month'],inplace=True)

In [31]:
listings_content17.drop(columns=['host_picture_url','host_neighbourhood','host_listings_count','city','calendar_updated'],inplace=True)

In [32]:
listings_content17.drop(columns='host_acceptance_rate',inplace=True)
listings_content17.drop(columns='host_total_listings_count',inplace=True)
listings_content17.drop(columns=['host_id','host_name'],inplace=True)
listings_content17.drop(columns='neighborhood_overview',inplace=True)
listings_content17.drop(columns=['name','notes','bed_type','latitude','longitude','number_of_reviews'],inplace=True)

In [33]:
listings_content17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3814 entries, 0 to 3813
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      3814 non-null   int64
 1   summary                 3742 non-null   object
 2   space                   3172 non-null   object
 3   description             3814 non-null   object
 4   transit                 2990 non-null   object
 5   access                  2978 non-null   object
 6   interaction             2990 non-null   object
 7   house_rules             3112 non-null   object
 8   host_response_time      3263 non-null   object
 9   host_response_rate      3263 non-null   object
 10  host_is_superhost       3814 non-null   object
 11  host_verifications      3814 non-null   object
 12  host_has_profile_pic    3814 non-null   object
 13  host_identity_verified  3814 non-null   object
 14  zipcode                 3760 non-null   float64
 15  property_type           3814 non-null   object
 16  accommodates            3814 non-null   int64
 17  bathrooms               3806 non-null   float64
 18  bedrooms                3813 non-null   float64
 19  beds                    3811 non-null   float64
 20  amenities               3814 non-null   object
 21  price                   3814 non-null   object
 22  security_deposit        1819 non-null   object
 23  cleaning_fee            2887 non-null   object
 24  guests_included         3814 non-null   int64
 25  extra_people            3814 non-null   object
 26  minimum_nights          3814 non-null   int64
 27  maximum_nights          3814 non-null   int64
 28  review_scores_rating    3436 non-null   float64
 29  instant_bookable        3814 non-null   object
 30  cancellation_policy     3814 non-null   object
dtypes: float64(5), int64(5), object(21)
memory usage: 923.8+ KB

In [34]:
listings_content17 = listings_content17.loc[(listings_content17.minimum_nights >= 1) & (listings_content17.maximum_nights <= 14)]
listings_content17.head(2)

,id,summary,space,description,transit,access,interaction,house_rules,host_response_time,host_response_rate,...,price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,review_scores_rating,instant_bookable,cancellation_policy
3,13031007,"Light, Bright, Eclectic 3 Bedroom Apartment in...",You have your own private entrance to this lig...,"Light, Bright, Eclectic 3 Bedroom Apartment in...",The red and blue max lines are fifteen minute ...,Private entrance through gated garden patio Wa...,You will probably not see me or if you do I wi...,Check-in after 4 pm Check-out at 11:00 am Fee...,within an hour,100%,...,$95.00,NaN,$50.00,4,$15.00,2,14,98.0,t,strict
11,13962174,Rest and rejuvenate from your adventures aroun...,"Modern, light-filled, and centrally-located. T...",Rest and rejuvenate from your adventures aroun...,The house is just a short walk to multiple bus...,You'll have your own key to the house and will...,I've lived in the city for 13 years and am hap...,- Please don't handle or play the musical inst...,NaN,NaN,...,$60.00,$100.00,$20.00,1,$0.00,2,7,100.0,f,moderate

In [35]:
pd.set_option('display.max_rows', 50)
listings_content17.property_type.value_counts()

House              413
Apartment          148
Other               16
Condominium         13
Guesthouse          11
Townhouse            8
Cabin                7
Camper/RV            5
Bungalow             5
Loft                 5
Bed & Breakfast      3
Boat                 2
Tent                 1
Chalet               1
Hut                  1
Name: property_type, dtype: int64

In [36]:
listings_content17 = listings_content17.loc[(listings_content17.property_type == 'House') | (listings_content17.property_type == 'Apartment') | (listings_content17.property_type == 'Guesthouse')|
                    (listings_content17.property_type == 'Other') | (listings_content17.property_type == 'Condominium')
                    | (listings_content17.property_type == 'Bungalow') | (listings_content17.property_type == 'Townhouse')|
                    (listings_content17.property_type == 'Cottage') | (listings_content17.property_type == 'Loft')| 
                    (listings_content17.property_type == 'Cabin') | (listings_content17.property_type == 'Bed & Breakfast')]

In [37]:
listings_content17 = listings_content17.loc[(listings_content17.bedrooms >= 1) & (listings_content17.bathrooms >= 1) & (listings_content17.beds >= 1)]

In [40]:
listings_content17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 571 entries, 3 to 3810
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      571 non-null    int64
 1   summary                 571 non-null    object
 2   space                   571 non-null    object
 3   description             571 non-null    object
 4   transit                 571 non-null    object
 5   access                  571 non-null    object
 6   interaction             571 non-null    object
 7   house_rules             571 non-null    object
 8   host_response_time      571 non-null    object
 9   host_response_rate      571 non-null    object
 10  host_is_superhost       571 non-null    object
 11  host_verifications      571 non-null    object
 12  host_has_profile_pic    571 non-null    object
 13  host_identity_verified  571 non-null    object
 14  zipcode                 557 non-null    float64
 15  property_type           571 non-null    object
 16  accommodates            571 non-null    int64
 17  bathrooms               571 non-null    float64
 18  bedrooms                571 non-null    float64
 19  beds                    571 non-null    float64
 20  amenities               571 non-null    object
 21  price                   571 non-null    object
 22  security_deposit        571 non-null    object
 23  cleaning_fee            571 non-null    object
 24  guests_included         571 non-null    int64
 25  extra_people            571 non-null    object
 26  minimum_nights          571 non-null    int64
 27  maximum_nights          571 non-null    int64
 28  review_scores_rating    495 non-null    float64
 29  instant_bookable        571 non-null    object
 30  cancellation_policy     571 non-null    object
dtypes: float64(5), int64(5), object(21)
memory usage: 142.8+ KB

In [39]:
values = {'summary':'', 'space':'', 'transit':'', 'access':'', 'interaction': '', 'house_rules': '', 
         'host_response_time':'','host_response_rate':'','security_deposit':'','cleaning_fee':''}
listings_content17 = listings_content17.fillna(value=values)

In [42]:
# All these listings are missing zip codes
listings_content17.loc[listings_content17.zipcode.isna()]

,id,summary,space,description,transit,access,interaction,house_rules,host_response_time,host_response_rate,...,price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,review_scores_rating,instant_bookable,cancellation_policy
250,13914180,This newly renovated daylight basement is in t...,This newly renovated daylight basement unit is...,This newly renovated daylight basement is in t...,Public transit is available right outside the ...,"As a guest, you will have full access to the e...",,,within an hour,100%,...,$95.00,$100.00,$40.00,3,$25.00,2,14,98.0,f,flexible
1064,12605354,Our 3 bedroom home in NE Portland is half a bl...,Cozy 3 bedroom home that is on a quiet road aw...,Our 3 bedroom home in NE Portland is half a bl...,There is great public transportation in Portla...,Guests have access to the house which includes...,"I will be available to welcome you, give you a...",- Please be quiet between the hours of 10pm an...,within an hour,100%,...,$169.00,$400.00,$40.00,4,$15.00,3,4,96.0,f,strict
1281,13879186,Welcome to my cozy home. We are one block from...,,Welcome to my cozy home. We are one block from...,,,,This is our full-time home and we are lovingly...,within a day,100%,...,$85.00,,$10.00,1,$0.00,2,3,100.0,f,flexible
1521,13390922,Brand new space on the border of Alberta Arts ...,"Brand new open concept space, inspired by my o...",Brand new space on the border of Alberta Arts ...,Plentiful street parking in front of the house...,Private entrance with electronic lock code upd...,I'm happy to help with local suggestions and a...,There's plenty of street parking in front of t...,within an hour,100%,...,$89.00,$100.00,$35.00,2,$35.00,1,8,99.0,f,moderate
1708,12203376,"Yes, the entire apartment is yours and yes, it...",,"Yes, the entire apartment is yours and yes, it...",,,,"Do what you will, if it harms no one. Bring a...",within an hour,100%,...,$129.00,,$30.00,1,$0.00,2,9,100.0,f,strict
1758,13771578,This apartment is a perfect getaway for you! L...,,This apartment is a perfect getaway for you! L...,,,,- Quiet hours between 11pm-8am,within a few hours,100%,...,$108.00,$250.00,$30.00,1,$0.00,2,6,94.0,f,strict
1773,14071519,Amazing location and gorgeous wrap around wind...,Guest can feel free to use the entire first fl...,Amazing location and gorgeous wrap around wind...,We are 1 block from the street car that can ta...,"You may access all common areas, kitchen, dini...",We love entertaining and usually have a little...,- Keep music volume to a minimum after 10pm,within an hour,100%,...,$89.00,,$30.00,1,$10.00,1,5,98.0,f,flexible
1976,8457976,Simple family friendly home. Queen bed and lar...,"A relaxed family home. A little hippie, a litt...",Simple family friendly home. Queen bed and lar...,Driveway is for you to use. There is street pa...,All of the top floor. Basement is off limits t...,"Yes, we'd be happy to assist you in any way we...","This is our home, thank you for treating it wi...",,,...,$125.00,$250.00,$50.00,1,$0.00,2,7,NaN,f,moderate
2338,15483739,"Our home is very walkable, close to Belmont an...",We absolutely love our home! It's a 1902 Portl...,"Our home is very walkable, close to Belmont an...",Parking on the street is plentiful. Driveway i...,"Guests have access to both bathrooms, sauna, k...",We both have flexible work schedules. Sometime...,"- vegetarian cooking only, may store meat in f...",within an hour,100%,...,$75.00,,$20.00,1,$0.00,1,10,NaN,f,flexible
2466,9494512,Welcome to our hideout. Whether you're explor...,,Welcome to our hideout. Whether you're explor...,,,,- We live fulltime in the upstairs unit. Plea...,within an hour,100%,...,$175.00,$500.00,$50.00,1,$0.00,2,5,100.0,f,moderate
3144,8146073,"This peaceful, quiet condo is perfect for coup...",,"This peaceful, quiet condo is perfect for coup...",The bus line directly to the city is right out...,All areas of the condo are accessible to guests.,I will be available for questions throughout y...,,within an hour,100%,...,$125.00,$300.00,$35.00,1,$0.00,1,4,100.0,f,flexible
3291,9014037,"Our room is ideal for the solo, adult traveler...","The upstairs room is quiet, bright and very co...","Our room is ideal for the solo, adult traveler...",Portland public transportation is very conveni...,There will be coffee available in the mornings...,We are friendly and willing to chat but will c...,"This is an adult, non-smoking, no pet facility...",within an hour,100%,...,$49.00,,,1,$0.00,2,14,100.0,t,moderate
3355,12008518,"My place is close to parks, coffee shops, Brew...",In the back of the apartment you will find a p...,"My place is close to parks, coffee shops, Brew...",With just a few steps away you have access to ...,You will be free to use the apartment as its y...,,,,,...,$65.00,$150.00,$10.00,3,$10.00,1,7,100.0,t,flexible
3541,16258796,Charming home built in 1920's in SE Portland’s...,The house has one bedroom available with queen...,Charming home built in 1920's in SE Portland’s...,There is a driveway and street parking availab...,You will have the entire home to yourself.,Feel free to contact me with any questions bef...,,within a day,83%,...,$69.00,,$25.00,1,$0.00,2,12,100.0,f,moderate

In [43]:
listings_content17 = listings_content17.rename(columns={'id': 'listing_id'}).reset_index(drop=True)
listings_content17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   listing_id              571 non-null    int64
 1   summary                 571 non-null    object
 2   space                   571 non-null    object
 3   description             571 non-null    object
 4   transit                 571 non-null    object
 5   access                  571 non-null    object
 6   interaction             571 non-null    object
 7   house_rules             571 non-null    object
 8   host_response_time      571 non-null    object
 9   host_response_rate      571 non-null    object
 10  host_is_superhost       571 non-null    object
 11  host_verifications      571 non-null    object
 12  host_has_profile_pic    571 non-null    object
 13  host_identity_verified  571 non-null    object
 14  zipcode                 557 non-null    float64
 15  property_type           571 non-null    object
 16  accommodates            571 non-null    int64
 17  bathrooms               571 non-null    float64
 18  bedrooms                571 non-null    float64
 19  beds                    571 non-null    float64
 20  amenities               571 non-null    object
 21  price                   571 non-null    object
 22  security_deposit        571 non-null    object
 23  cleaning_fee            571 non-null    object
 24  guests_included         571 non-null    int64
 25  extra_people            571 non-null    object
 26  minimum_nights          571 non-null    int64
 27  maximum_nights          571 non-null    int64
 28  review_scores_rating    495 non-null    float64
 29  instant_bookable        571 non-null    object
 30  cancellation_policy     571 non-null    object
dtypes: float64(5), int64(5), object(21)
memory usage: 138.4+ KB

In [44]:
listings_content17.to_csv('listingscontent_cleaned2017.csv',index=False)